version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "fucking never"
    ignore:
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]