import { db } from '$lib/server/database';
import { ioQueue } from '$lib/server/queue/index';
import { sysLog } from '$lib/server/logger';
import { getActiveSchema } from '$lib/server/ontology';
import { evaluateTextIdentity } from '$lib/server/matcher';

/**
 * The ItemOps sandbox. Wraps raw Prisma mutations in idempotent safety checks 
 * (e.g., verifying isAutoGenerated) so plugins don't overwrite manual user corrections.
 */
export function createItemOpsSandbox() {
    return {
        async setAttribute(itemId: number, key: string, value: string) {
            const existing = await db.kVP.findFirst({ where: { itemId, key } });
            if (existing) {
                if (!existing.isAutoGenerated) return false;
                if (existing.value !== value) {
                    await db.kVP.update({ where: { id: existing.id }, data: { value } });
                    return true;
                }
                return false;
            }
            await db.kVP.create({ data: { itemId, key, value, isAutoGenerated: true } });
            return true;
        },
        async attachDocument(itemId: number, doc: { title: string, source: string, path: string, extracts?: string, type?: string }) {
            const existing = await db.document.findFirst({ where: { itemId, path: doc.path } });
            if (existing) return false;
            await db.document.create({ data: { itemId, ...doc, extracts: doc.extracts || '', type: doc.type || 'link' } });
            return true;
        },
        async getSchema(inventoryId: number, categoryId?: number | null) {
            return await getActiveSchema(inventoryId, categoryId, false);
        },
        compareTitles(scannedTitle: string, dbTitle: string, scanDesc: string = '', dbDesc: string = '', category: string = '') {
            return evaluateTextIdentity(scannedTitle, scanDesc, dbTitle, dbDesc, category);
        },
        getFuzzyAttribute(item: any, keywords: string[]) {
            if (!item.attributes) return null;
            const match = item.attributes.find((a: any) => {
                const keyLower = (a.key || '').toLowerCase().replace(/[^a-z0-9]/g, '');
                return keywords.some(kw => keyLower.includes(kw.toLowerCase().replace(/[^a-z0-9]/g, '')));
            });
            return match ? match.value : null;
        },
        async processPhoto(photoId: number, options: { removeBackground?: boolean, extractColors?: boolean }) {
            const photo = await db.photo.findUnique({ where: { id: photoId } });
            if (!photo || !photo.orgPath) return false;
            const { generatePhotoDerivatives } = await import('$lib/server/imageProcessor');
            ioQueue.add(async () => {
                try {
                    const tracking = { targetType: 'item' as const, targetId: photo.itemId! };
                    const updates = await generatePhotoDerivatives(photo, photo.orgPath!, options.extractColors ?? true, tracking, null, options.removeBackground ?? true);
                    if (Object.keys(updates).length > 0) {
                        await db.photo.update({ where: { id: photoId }, data: updates });
                    }
                } catch(e) { sysLog.error(`[itemOps] processPhoto failed for photo ${photoId}`, e); }
            }, { targetType: 'item', targetId: photo.itemId!, description: `Processing photo ${photoId}` });
            return true;
        },
        async fetchAndStoreWebpage(url: string, itemId: number) {
            const { downloadAndStoreDocuments } = await import('$lib/server/urldownloader');
            const { uploadsDiskFolder, uploadsWebFolder, uploadsRemoteSite } = await import('$lib/server/constants');
            return ioQueue.add(async () => {
                try { await downloadAndStoreDocuments({ itemId }, uploadsRemoteSite, { urls: url }, uploadsDiskFolder, uploadsWebFolder, '', 0); } catch (err) { sysLog.error(`[itemOps] Failed to fetch and store webpage ${url}:`, err); throw err; }
            }, { targetType: 'item', targetId: itemId, description: `Archiving webpage: ${url}` });
        }
    };
}