import { db } from '$lib/server/database';
import { logActivity } from '$lib/server/logger';

const KEEP_N_SNAPSHOTS = 5;

export async function takeSnapshot(itemId: number, source: string = "System") {
    try {
        const item = await db.item.findUnique({
            where: { id: itemId },
            include: {
                attributes: true,
                tags: true,
                locations: true,
                photos: true,
                documents: true
            }
        });

        if (!item) return;

        // We serialize the entire Prisma object. Any new scalar columns
        // added to the schema in the future are automatically captured here.
        await db.itemSnapshot.create({
            data: {
                itemId,
                source,
                snapshotJson: JSON.stringify(item)
            }
        });

        // Prune old snapshots
        const snapshots = await db.itemSnapshot.findMany({
            where: { itemId },
            orderBy: { createdAt: 'desc' },
            select: { id: true }
        });

        if (snapshots.length > KEEP_N_SNAPSHOTS) {
            const toDelete = snapshots.slice(KEEP_N_SNAPSHOTS).map(s => s.id);
            await db.itemSnapshot.deleteMany({
                where: { id: { in: toDelete } }
            });
        }
    } catch (e) {
        console.error(`[ItemHistory] Failed to take snapshot for item ${itemId}:`, e);
    }
}

export async function rollbackToSnapshot(snapshotId: number) {
    const snapshot = await db.itemSnapshot.findUnique({
        where: { id: snapshotId },
        include: { item: true }
    });

    if (!snapshot) throw new Error("Snapshot not found");

    const data = JSON.parse(snapshot.snapshotJson);
    const itemId = snapshot.itemId;

    // DYNAMIC FIELD EXTRACTION:
    // Extract immutable fields and relations. Everything leftover (...dynamicScalars) 
    // represents the raw schema columns. This natively future-proofs the rollback.
    const { 
        id, createdAt, updatedAt, inventoryId, authorId, clientId, 
        attributes, tags, locations, photos, documents, usage, logs, timelineNotes, snapshots, 
        ...dynamicScalars 
    } = data;

    // Assemble the transaction operations dynamically
    const txOps: any[] = [
        db.kVP.deleteMany({ where: { itemId } }),
        db.itemsInContainer.deleteMany({ where: { itemId } }),
        
        // Delete any photos/docs that were added AFTER the snapshot
        db.photo.deleteMany({ where: { itemId, id: { notIn: photos?.map((p: any) => p.id) || [] } } }),
        db.document.deleteMany({ where: { itemId, id: { notIn: documents?.map((d: any) => d.id) || [] } } })
    ];

    // Restore the exact state of photos that existed during the snapshot
    if (photos) {
        for (const p of photos) {
            const { id: pId, itemId: _i, createdAt: _c, updatedAt: _u, ...pData } = p;
            txOps.push(db.photo.upsert({ where: { id: pId }, update: pData, create: { id: pId, itemId, ...pData } }));
        }
    }

    // Restore the exact state of documents that existed during the snapshot
    if (documents) {
        for (const d of documents) {
            const { id: dId, itemId: _i, createdAt: _c, updatedAt: _u, ...dData } = d;
            txOps.push(db.document.upsert({ where: { id: dId }, update: dData, create: { id: dId, itemId, ...dData } }));
        }
    }

    txOps.push(db.item.update({
            where: { id: itemId },
            data: {
                ...dynamicScalars,
                attributes: { create: attributes?.map((a: any) => ({ key: a.key, value: a.value, isAutoGenerated: a.isAutoGenerated })) || [] },
                locations: { create: locations?.map((l: any) => ({ containerId: l.containerId, spatialMap: l.spatialMap })) || [] },
                tags: { set: tags?.map((t: any) => ({ id: t.id })) || [] }
            }
    }));

    await db.$transaction(txOps);

    await logActivity(itemId, 'Rollback', `Restored item state from: ${snapshot.source}`, 'success');
}
