/**
 * Core mathematical utilities for handling 4-point oriented bounding boxes (Polygons)
 * generated by the Vision Model, allowing us to handle skew and rotation.
 */

export type Point = [number, number]; // [x, y] in percentages (0-1000)
export type Polygon = [Point, Point, Point, Point];

/**
 * Converts an oriented 4-point polygon into a standard axis-aligned bounding box.
 * Useful for fallback cropping logic where true perspective warping isn't available.
 * Returns: [top, left, bottom, right]
 */
export function polygonToAxisAlignedBox(polygon: Polygon): [number, number, number, number] {
    const xs = polygon.map(p => p[0]);
    const ys = polygon.map(p => p[1]);
    
    return [
        Math.min(...ys), // top
        Math.min(...xs), // left
        Math.max(...ys), // bottom
        Math.max(...xs)  // right
    ];
}

/**
 * Calculates the rough rotation angle (in degrees) of a polygon.
 * Assumes the first two points represent the top edge.
 */
export function calculatePolygonRotation(polygon: Polygon): number {
    const [p1, p2] = polygon;
    const dx = p2[0] - p1[0];
    const dy = p2[1] - p1[1];
    
    let angle = Math.atan2(dy, dx) * (180 / Math.PI);
    return angle;
}

/**
 * Checks if a specific point (e.g., user tap) falls inside a polygon.
 * Uses the ray-casting algorithm.
 */
export function isPointInPolygon(point: Point, polygon: Polygon): boolean {
    const [x, y] = point;
    let inside = false;
    for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
        const [xi, yi] = polygon[i];
        const [xj, yj] = polygon[j];
        
        const intersect = ((yi > y) !== (yj > y)) && (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
        if (intersect) inside = !inside;
    }
    return inside;
}